"""add article url category quality_score

Revision ID: 785a6079e21a
Revises: 11b9334260e7
Create Date: 2026-05-26 14:39:29.667335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785a6079e21a'
down_revision: Union[str, Sequence[str], None] = '11b9334260e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_articles', sa.Column('url', sa.String(length=2048), nullable=True))
    op.add_column('ai_articles', sa.Column('category', sa.String(length=120), nullable=True))
    op.add_column('ai_articles', sa.Column('quality_score', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_ai_article_source_url', 'ai_articles', ['source_id', 'url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ai_article_source_url', 'ai_articles', type_='unique')
    op.drop_column('ai_articles', 'quality_score')
    op.drop_column('ai_articles', 'category')
    op.drop_column('ai_articles', 'url')
    # ### end Alembic commands ###
