type User {
  id: ID!
  email: String!
  nickname: String
  avatarUrl: String
  createdAt: String!
  roles: [Role!]!
}

type Role {
  id: ID!
  name: String!
  description: String
}

type AuthPayload {
  token: String!
  user: User!
}

extend type Query {
  me: User
}

extend type Mutation {
  login(email: String!, password: String!): AuthPayload!
  register(email: String!, password: String!, nickname: String): AuthPayload!
  updateProfile(nickname: String, avatarUrl: String): User!
  changePassword(currentPassword: String!, newPassword: String!): Boolean!
}
