/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
  'query ChatSessions($limit: Int, $offset: Int, $search: String) {\n  chatSessions(limit: $limit, offset: $offset, search: $search) {\n    id\n    title\n    status\n    createdAt\n    updatedAt\n    lastMessageAt\n  }\n}\n\nquery ChatSession($id: ID!, $limit: Int, $offset: Int) {\n  chatSession(id: $id) {\n    id\n    title\n    status\n    createdAt\n    updatedAt\n    lastMessageAt\n    messages(limit: $limit, offset: $offset) {\n      id\n      role\n      status\n      content\n      createdAt\n    }\n  }\n}\n\nmutation StartChatSession($input: StartChatSessionInput) {\n  startChatSession(input: $input) {\n    id\n    title\n    status\n    createdAt\n    updatedAt\n    lastMessageAt\n  }\n}\n\nmutation SendChatMessage($sessionId: ID!, $content: String!) {\n  sendChatMessage(sessionId: $sessionId, content: $content) {\n    session {\n      id\n      title\n      status\n      createdAt\n      updatedAt\n      lastMessageAt\n    }\n    userMessage {\n      id\n      role\n      status\n      content\n      createdAt\n    }\n    assistantMessage {\n      id\n      role\n      status\n      content\n      createdAt\n    }\n  }\n}\n\nmutation ArchiveChatSession($sessionId: ID!) {\n  archiveChatSession(sessionId: $sessionId) {\n    id\n    status\n    updatedAt\n  }\n}\n\nmutation DeleteChatSession($sessionId: ID!) {\n  deleteChatSession(sessionId: $sessionId)\n}\n\nsubscription ChatSessionStream($sessionId: ID!, $messageId: ID!) {\n  chatSessionStream(sessionId: $sessionId, messageId: $messageId) {\n    eventId\n    seq\n    type\n    sessionId\n    messageId\n    chunk\n    done\n    createdAt\n    model\n    error\n  }\n}': typeof types.ChatSessionsDocument;
  'query Me {\n  me {\n    id\n    email\n    nickname\n    avatarUrl\n    createdAt\n    roles {\n      id\n      name\n    }\n  }\n}\n\nmutation Login($email: String!, $password: String!) {\n  login(email: $email, password: $password) {\n    token\n    user {\n      id\n      email\n      nickname\n      avatarUrl\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nmutation Register($email: String!, $password: String!) {\n  register(email: $email, password: $password) {\n    token\n    user {\n      id\n      email\n      nickname\n      avatarUrl\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nmutation UpdateProfile($nickname: String, $avatarUrl: String) {\n  updateProfile(nickname: $nickname, avatarUrl: $avatarUrl) {\n    id\n    email\n    nickname\n    avatarUrl\n    roles {\n      id\n      name\n    }\n  }\n}\n\nmutation ChangePassword($currentPassword: String!, $newPassword: String!) {\n  changePassword(currentPassword: $currentPassword, newPassword: $newPassword)\n}': typeof types.MeDocument;
  'query Posts($topic: String, $subtopic: String, $status: PostStatus, $search: String, $sortBy: PostSortField, $sortDirection: SortDirection, $mine: Boolean, $limit: Int, $offset: Int) {\n  posts(\n    topic: $topic\n    subtopic: $subtopic\n    status: $status\n    search: $search\n    sortBy: $sortBy\n    sortDirection: $sortDirection\n    mine: $mine\n    limit: $limit\n    offset: $offset\n  ) {\n    id\n    title\n    content\n    topic\n    subtopic\n    seriesKey\n    seriesOrder\n    status\n    publishedAt\n    source\n    wordCount\n    generationBatchId\n    createdAt\n    updatedAt\n    author {\n      id\n      email\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nquery PostsTotal($topic: String, $subtopic: String, $status: PostStatus, $search: String, $mine: Boolean) {\n  postsTotal(\n    topic: $topic\n    subtopic: $subtopic\n    status: $status\n    search: $search\n    mine: $mine\n  )\n}\n\nquery Post($id: ID!) {\n  post(id: $id) {\n    id\n    title\n    content\n    topic\n    subtopic\n    seriesKey\n    seriesOrder\n    status\n    publishedAt\n    source\n    wordCount\n    generationBatchId\n    createdAt\n    updatedAt\n    author {\n      id\n      email\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nquery PostNeighbors($id: ID!) {\n  postNeighbors(id: $id) {\n    prev {\n      id\n      title\n      seriesKey\n      seriesOrder\n    }\n    next {\n      id\n      title\n      seriesKey\n      seriesOrder\n    }\n  }\n}\n\nmutation CreatePost($input: CreatePostInput!) {\n  createPost(input: $input) {\n    id\n    title\n    status\n    createdAt\n  }\n}\n\nmutation UpdatePost($id: ID!, $input: UpdatePostInput!) {\n  updatePost(id: $id, input: $input) {\n    id\n    title\n    status\n    updatedAt\n  }\n}\n\nmutation DeletePost($id: ID!) {\n  deletePost(id: $id)\n}': typeof types.PostsDocument;
};
const documents: Documents = {
  'query ChatSessions($limit: Int, $offset: Int, $search: String) {\n  chatSessions(limit: $limit, offset: $offset, search: $search) {\n    id\n    title\n    status\n    createdAt\n    updatedAt\n    lastMessageAt\n  }\n}\n\nquery ChatSession($id: ID!, $limit: Int, $offset: Int) {\n  chatSession(id: $id) {\n    id\n    title\n    status\n    createdAt\n    updatedAt\n    lastMessageAt\n    messages(limit: $limit, offset: $offset) {\n      id\n      role\n      status\n      content\n      createdAt\n    }\n  }\n}\n\nmutation StartChatSession($input: StartChatSessionInput) {\n  startChatSession(input: $input) {\n    id\n    title\n    status\n    createdAt\n    updatedAt\n    lastMessageAt\n  }\n}\n\nmutation SendChatMessage($sessionId: ID!, $content: String!) {\n  sendChatMessage(sessionId: $sessionId, content: $content) {\n    session {\n      id\n      title\n      status\n      createdAt\n      updatedAt\n      lastMessageAt\n    }\n    userMessage {\n      id\n      role\n      status\n      content\n      createdAt\n    }\n    assistantMessage {\n      id\n      role\n      status\n      content\n      createdAt\n    }\n  }\n}\n\nmutation ArchiveChatSession($sessionId: ID!) {\n  archiveChatSession(sessionId: $sessionId) {\n    id\n    status\n    updatedAt\n  }\n}\n\nmutation DeleteChatSession($sessionId: ID!) {\n  deleteChatSession(sessionId: $sessionId)\n}\n\nsubscription ChatSessionStream($sessionId: ID!, $messageId: ID!) {\n  chatSessionStream(sessionId: $sessionId, messageId: $messageId) {\n    eventId\n    seq\n    type\n    sessionId\n    messageId\n    chunk\n    done\n    createdAt\n    model\n    error\n  }\n}':
    types.ChatSessionsDocument,
  'query Me {\n  me {\n    id\n    email\n    nickname\n    avatarUrl\n    createdAt\n    roles {\n      id\n      name\n    }\n  }\n}\n\nmutation Login($email: String!, $password: String!) {\n  login(email: $email, password: $password) {\n    token\n    user {\n      id\n      email\n      nickname\n      avatarUrl\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nmutation Register($email: String!, $password: String!) {\n  register(email: $email, password: $password) {\n    token\n    user {\n      id\n      email\n      nickname\n      avatarUrl\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nmutation UpdateProfile($nickname: String, $avatarUrl: String) {\n  updateProfile(nickname: $nickname, avatarUrl: $avatarUrl) {\n    id\n    email\n    nickname\n    avatarUrl\n    roles {\n      id\n      name\n    }\n  }\n}\n\nmutation ChangePassword($currentPassword: String!, $newPassword: String!) {\n  changePassword(currentPassword: $currentPassword, newPassword: $newPassword)\n}':
    types.MeDocument,
  'query Posts($topic: String, $subtopic: String, $status: PostStatus, $search: String, $sortBy: PostSortField, $sortDirection: SortDirection, $mine: Boolean, $limit: Int, $offset: Int) {\n  posts(\n    topic: $topic\n    subtopic: $subtopic\n    status: $status\n    search: $search\n    sortBy: $sortBy\n    sortDirection: $sortDirection\n    mine: $mine\n    limit: $limit\n    offset: $offset\n  ) {\n    id\n    title\n    content\n    topic\n    subtopic\n    seriesKey\n    seriesOrder\n    status\n    publishedAt\n    source\n    wordCount\n    generationBatchId\n    createdAt\n    updatedAt\n    author {\n      id\n      email\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nquery PostsTotal($topic: String, $subtopic: String, $status: PostStatus, $search: String, $mine: Boolean) {\n  postsTotal(\n    topic: $topic\n    subtopic: $subtopic\n    status: $status\n    search: $search\n    mine: $mine\n  )\n}\n\nquery Post($id: ID!) {\n  post(id: $id) {\n    id\n    title\n    content\n    topic\n    subtopic\n    seriesKey\n    seriesOrder\n    status\n    publishedAt\n    source\n    wordCount\n    generationBatchId\n    createdAt\n    updatedAt\n    author {\n      id\n      email\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nquery PostNeighbors($id: ID!) {\n  postNeighbors(id: $id) {\n    prev {\n      id\n      title\n      seriesKey\n      seriesOrder\n    }\n    next {\n      id\n      title\n      seriesKey\n      seriesOrder\n    }\n  }\n}\n\nmutation CreatePost($input: CreatePostInput!) {\n  createPost(input: $input) {\n    id\n    title\n    status\n    createdAt\n  }\n}\n\nmutation UpdatePost($id: ID!, $input: UpdatePostInput!) {\n  updatePost(id: $id, input: $input) {\n    id\n    title\n    status\n    updatedAt\n  }\n}\n\nmutation DeletePost($id: ID!) {\n  deletePost(id: $id)\n}':
    types.PostsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: 'query ChatSessions($limit: Int, $offset: Int, $search: String) {\n  chatSessions(limit: $limit, offset: $offset, search: $search) {\n    id\n    title\n    status\n    createdAt\n    updatedAt\n    lastMessageAt\n  }\n}\n\nquery ChatSession($id: ID!, $limit: Int, $offset: Int) {\n  chatSession(id: $id) {\n    id\n    title\n    status\n    createdAt\n    updatedAt\n    lastMessageAt\n    messages(limit: $limit, offset: $offset) {\n      id\n      role\n      status\n      content\n      createdAt\n    }\n  }\n}\n\nmutation StartChatSession($input: StartChatSessionInput) {\n  startChatSession(input: $input) {\n    id\n    title\n    status\n    createdAt\n    updatedAt\n    lastMessageAt\n  }\n}\n\nmutation SendChatMessage($sessionId: ID!, $content: String!) {\n  sendChatMessage(sessionId: $sessionId, content: $content) {\n    session {\n      id\n      title\n      status\n      createdAt\n      updatedAt\n      lastMessageAt\n    }\n    userMessage {\n      id\n      role\n      status\n      content\n      createdAt\n    }\n    assistantMessage {\n      id\n      role\n      status\n      content\n      createdAt\n    }\n  }\n}\n\nmutation ArchiveChatSession($sessionId: ID!) {\n  archiveChatSession(sessionId: $sessionId) {\n    id\n    status\n    updatedAt\n  }\n}\n\nmutation DeleteChatSession($sessionId: ID!) {\n  deleteChatSession(sessionId: $sessionId)\n}\n\nsubscription ChatSessionStream($sessionId: ID!, $messageId: ID!) {\n  chatSessionStream(sessionId: $sessionId, messageId: $messageId) {\n    eventId\n    seq\n    type\n    sessionId\n    messageId\n    chunk\n    done\n    createdAt\n    model\n    error\n  }\n}',
): (typeof documents)['query ChatSessions($limit: Int, $offset: Int, $search: String) {\n  chatSessions(limit: $limit, offset: $offset, search: $search) {\n    id\n    title\n    status\n    createdAt\n    updatedAt\n    lastMessageAt\n  }\n}\n\nquery ChatSession($id: ID!, $limit: Int, $offset: Int) {\n  chatSession(id: $id) {\n    id\n    title\n    status\n    createdAt\n    updatedAt\n    lastMessageAt\n    messages(limit: $limit, offset: $offset) {\n      id\n      role\n      status\n      content\n      createdAt\n    }\n  }\n}\n\nmutation StartChatSession($input: StartChatSessionInput) {\n  startChatSession(input: $input) {\n    id\n    title\n    status\n    createdAt\n    updatedAt\n    lastMessageAt\n  }\n}\n\nmutation SendChatMessage($sessionId: ID!, $content: String!) {\n  sendChatMessage(sessionId: $sessionId, content: $content) {\n    session {\n      id\n      title\n      status\n      createdAt\n      updatedAt\n      lastMessageAt\n    }\n    userMessage {\n      id\n      role\n      status\n      content\n      createdAt\n    }\n    assistantMessage {\n      id\n      role\n      status\n      content\n      createdAt\n    }\n  }\n}\n\nmutation ArchiveChatSession($sessionId: ID!) {\n  archiveChatSession(sessionId: $sessionId) {\n    id\n    status\n    updatedAt\n  }\n}\n\nmutation DeleteChatSession($sessionId: ID!) {\n  deleteChatSession(sessionId: $sessionId)\n}\n\nsubscription ChatSessionStream($sessionId: ID!, $messageId: ID!) {\n  chatSessionStream(sessionId: $sessionId, messageId: $messageId) {\n    eventId\n    seq\n    type\n    sessionId\n    messageId\n    chunk\n    done\n    createdAt\n    model\n    error\n  }\n}'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: 'query Me {\n  me {\n    id\n    email\n    nickname\n    avatarUrl\n    createdAt\n    roles {\n      id\n      name\n    }\n  }\n}\n\nmutation Login($email: String!, $password: String!) {\n  login(email: $email, password: $password) {\n    token\n    user {\n      id\n      email\n      nickname\n      avatarUrl\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nmutation Register($email: String!, $password: String!) {\n  register(email: $email, password: $password) {\n    token\n    user {\n      id\n      email\n      nickname\n      avatarUrl\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nmutation UpdateProfile($nickname: String, $avatarUrl: String) {\n  updateProfile(nickname: $nickname, avatarUrl: $avatarUrl) {\n    id\n    email\n    nickname\n    avatarUrl\n    roles {\n      id\n      name\n    }\n  }\n}\n\nmutation ChangePassword($currentPassword: String!, $newPassword: String!) {\n  changePassword(currentPassword: $currentPassword, newPassword: $newPassword)\n}',
): (typeof documents)['query Me {\n  me {\n    id\n    email\n    nickname\n    avatarUrl\n    createdAt\n    roles {\n      id\n      name\n    }\n  }\n}\n\nmutation Login($email: String!, $password: String!) {\n  login(email: $email, password: $password) {\n    token\n    user {\n      id\n      email\n      nickname\n      avatarUrl\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nmutation Register($email: String!, $password: String!) {\n  register(email: $email, password: $password) {\n    token\n    user {\n      id\n      email\n      nickname\n      avatarUrl\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nmutation UpdateProfile($nickname: String, $avatarUrl: String) {\n  updateProfile(nickname: $nickname, avatarUrl: $avatarUrl) {\n    id\n    email\n    nickname\n    avatarUrl\n    roles {\n      id\n      name\n    }\n  }\n}\n\nmutation ChangePassword($currentPassword: String!, $newPassword: String!) {\n  changePassword(currentPassword: $currentPassword, newPassword: $newPassword)\n}'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: 'query Posts($topic: String, $subtopic: String, $status: PostStatus, $search: String, $sortBy: PostSortField, $sortDirection: SortDirection, $mine: Boolean, $limit: Int, $offset: Int) {\n  posts(\n    topic: $topic\n    subtopic: $subtopic\n    status: $status\n    search: $search\n    sortBy: $sortBy\n    sortDirection: $sortDirection\n    mine: $mine\n    limit: $limit\n    offset: $offset\n  ) {\n    id\n    title\n    content\n    topic\n    subtopic\n    seriesKey\n    seriesOrder\n    status\n    publishedAt\n    source\n    wordCount\n    generationBatchId\n    createdAt\n    updatedAt\n    author {\n      id\n      email\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nquery PostsTotal($topic: String, $subtopic: String, $status: PostStatus, $search: String, $mine: Boolean) {\n  postsTotal(\n    topic: $topic\n    subtopic: $subtopic\n    status: $status\n    search: $search\n    mine: $mine\n  )\n}\n\nquery Post($id: ID!) {\n  post(id: $id) {\n    id\n    title\n    content\n    topic\n    subtopic\n    seriesKey\n    seriesOrder\n    status\n    publishedAt\n    source\n    wordCount\n    generationBatchId\n    createdAt\n    updatedAt\n    author {\n      id\n      email\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nquery PostNeighbors($id: ID!) {\n  postNeighbors(id: $id) {\n    prev {\n      id\n      title\n      seriesKey\n      seriesOrder\n    }\n    next {\n      id\n      title\n      seriesKey\n      seriesOrder\n    }\n  }\n}\n\nmutation CreatePost($input: CreatePostInput!) {\n  createPost(input: $input) {\n    id\n    title\n    status\n    createdAt\n  }\n}\n\nmutation UpdatePost($id: ID!, $input: UpdatePostInput!) {\n  updatePost(id: $id, input: $input) {\n    id\n    title\n    status\n    updatedAt\n  }\n}\n\nmutation DeletePost($id: ID!) {\n  deletePost(id: $id)\n}',
): (typeof documents)['query Posts($topic: String, $subtopic: String, $status: PostStatus, $search: String, $sortBy: PostSortField, $sortDirection: SortDirection, $mine: Boolean, $limit: Int, $offset: Int) {\n  posts(\n    topic: $topic\n    subtopic: $subtopic\n    status: $status\n    search: $search\n    sortBy: $sortBy\n    sortDirection: $sortDirection\n    mine: $mine\n    limit: $limit\n    offset: $offset\n  ) {\n    id\n    title\n    content\n    topic\n    subtopic\n    seriesKey\n    seriesOrder\n    status\n    publishedAt\n    source\n    wordCount\n    generationBatchId\n    createdAt\n    updatedAt\n    author {\n      id\n      email\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nquery PostsTotal($topic: String, $subtopic: String, $status: PostStatus, $search: String, $mine: Boolean) {\n  postsTotal(\n    topic: $topic\n    subtopic: $subtopic\n    status: $status\n    search: $search\n    mine: $mine\n  )\n}\n\nquery Post($id: ID!) {\n  post(id: $id) {\n    id\n    title\n    content\n    topic\n    subtopic\n    seriesKey\n    seriesOrder\n    status\n    publishedAt\n    source\n    wordCount\n    generationBatchId\n    createdAt\n    updatedAt\n    author {\n      id\n      email\n      roles {\n        id\n        name\n      }\n    }\n  }\n}\n\nquery PostNeighbors($id: ID!) {\n  postNeighbors(id: $id) {\n    prev {\n      id\n      title\n      seriesKey\n      seriesOrder\n    }\n    next {\n      id\n      title\n      seriesKey\n      seriesOrder\n    }\n  }\n}\n\nmutation CreatePost($input: CreatePostInput!) {\n  createPost(input: $input) {\n    id\n    title\n    status\n    createdAt\n  }\n}\n\nmutation UpdatePost($id: ID!, $input: UpdatePostInput!) {\n  updatePost(id: $id, input: $input) {\n    id\n    title\n    status\n    updatedAt\n  }\n}\n\nmutation DeletePost($id: ID!) {\n  deletePost(id: $id)\n}'];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
